# Allows loading EQ settings from a file generated by RoomEQ Wizard (REW) and
# sending them to a PEQ.
class MB::EQLoader::EQFile
  def initialize(filename)
    @bands = []

    File.open(filename, 'rt') do
      raise NotImplementedError, 'TODO'
    end
  end

  # Sends the loaded EQ data to the given +peq+ object (an MB::EQLoader::PEQ).
  def apply(peq, first_band: 1)
    @bands.each_with_index do |b, idx|
      peq.set_band(band: idx + first_band, **b)
    end
  end
end
